language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t tienduynguyen/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true -it tienduynguyen/multi-docker-test yarn test --coverage

branches:
  only:
    - master
